name: huear_fixed
description: "An AR-based color identification app for color blind users."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"  # Explicit version range for Dart 3.8

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cupertino_icons: ^1.0.6
  camera: ^0.11.1
  image: ^4.1.4
  palette_generator:
  path_provider: ^2.1.1
  photo_manager: ^3.1.0
  shared_preferences: ^2.2.2
  timeago: ^3.5.0
  vector_math: ^2.1.4
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  path: ^1.8.3
  google_mlkit_object_detection: ^0.11.0
  screenshot: ^2.5.0
  permission_handler: ^12.0.0
  permission_handler_android: ^13.0.1
  image_picker: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

    