// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD87ag7ES-9DKaIruDEs74ffv7ImXLKtU',
    appId: '1:857798825578:web:feb4fd660b030a960c9c13',
    messagingSenderId: '857798825578',
    projectId: 'huearapp-auth',
    authDomain: 'huearapp-auth.firebaseapp.com',
    storageBucket: 'huearapp-auth.firebasestorage.app',
    measurementId: 'G-QM52MM0JH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzs3-eDHiu60kHzh-kulfXspZKsPSLgck',
    appId: '1:857798825578:android:cc62978c3b3b7ba80c9c13',
    messagingSenderId: '857798825578',
    projectId: 'huearapp-auth',
    storageBucket: 'huearapp-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASeK5BChnIZQ3xVUFtEnb54_asst6rWbs',
    appId: '1:857798825578:ios:bfc94e5c4edcccb20c9c13',
    messagingSenderId: '857798825578',
    projectId: 'huearapp-auth',
    storageBucket: 'huearapp-auth.firebasestorage.app',
    iosBundleId: 'com.example.huearappDevelop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASeK5BChnIZQ3xVUFtEnb54_asst6rWbs',
    appId: '1:857798825578:ios:bfc94e5c4edcccb20c9c13',
    messagingSenderId: '857798825578',
    projectId: 'huearapp-auth',
    storageBucket: 'huearapp-auth.firebasestorage.app',
    iosBundleId: 'com.example.huearappDevelop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD87ag7ES-9DKaIruDEs74ffv7ImXLKtU',
    appId: '1:857798825578:web:c4f99694e98692590c9c13',
    messagingSenderId: '857798825578',
    projectId: 'huearapp-auth',
    authDomain: 'huearapp-auth.firebaseapp.com',
    storageBucket: 'huearapp-auth.firebasestorage.app',
    measurementId: 'G-VCXPPCJ1M6',
  );
}
